[package]
name = "codegen"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
json5 = "1.3.1"
regex = "1.13.1"
serde = { version = "1.0.229", features = ["derive"] }

[lints.rust]
warnings = "deny"
unsafe_code = "forbid"
trivial_casts = "deny"
trivial_numeric_casts = "deny"
unused_extern_crates = "deny"
unused_import_braces = "deny"
unused_qualifications = "deny"
unused_must_use = "deny"
missing_docs = "allow"

[lints.clippy]
all = { level = "deny", priority = -1 }
cargo = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
enum_glob_use = "allow"
cargo_common_metadata = "allow" #FIXME!
redundant_closure_for_method_calls = "allow"
should_panic_without_expect = "allow"
manual_range_contains = "allow"
missing_errors_doc = "allow"
