[package]
name = "codegen"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
databake = { version = "0.2.1", features = ["derive"] }
json5 = "1.3.1"
regex = "1.13.1"
serde = { version = "1.0.229", features = ["derive"] }
strum = { version = "0.28.0", features = ["derive"] }
stonetop = { version = "0.1.0", path = "../stonetop", features = ["codegen"] }

[dev-dependencies]
# The tests compare the baked file's content with the json5, so they need the baked file.
stonetop = { version = "0.1.0", path = "../stonetop", features = ["codegen", "ssr"] }

[lints.rust]
warnings = "deny"
unsafe_code = "forbid"
trivial_casts = "deny"
trivial_numeric_casts = "deny"
unused_extern_crates = "deny"
unused_import_braces = "deny"
unused_qualifications = "deny"
unused_must_use = "deny"
missing_docs = "allow"

[lints.clippy]
all = { level = "deny", priority = -1 }
cargo = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
enum_glob_use = "allow"
# serde and databake use different versions of syn, though the most recent version of ICU4X
# seems to use syn 3.0 (as serde does)
multiple_crate_versions = "allow"
cargo_common_metadata = "allow" #FIXME!
redundant_closure_for_method_calls = "allow"
should_panic_without_expect = "allow"
manual_range_contains = "allow"
missing_errors_doc = "allow"
