#!/bin/sh
set -e
set -x
export RUSTDOCFLAGS=-Dwarnings
typos
cargo fmt -- --check
cargo doc --workspace --no-deps --document-private-items --all-features
cargo clippy --profile=test --all-targets --all-features --no-deps
cargo clippy --profile=release --all-targets --all-features --no-deps
cargo nextest run --run-ignored all --all-features --cargo-quiet --cargo-quiet --status-level none
