pub enum PlaybookKey {
    TheBlessed,
    TheFox,
    TheHeavy,
    TheJudge,
    TheLightbearer,
    TheMarshal,
    TheRanger,
    TheSeeker,
    TheWouldBeHero,
}
pub enum ItemKey {
    // Backgrounds for the Blessed
    Initiate,
    RaisedByWolves,
    Vessel,

    // Backgrounds for the Fox
    TheNatural,
    ALifeOfCrime,
    TheProdigalReturned,

    // Backgrounds for the Heavy
    Sheriff,
    BloodSoakedPast,
    StormMarked,

    // Backgrounds for the Judge
    Legacy,
    Missionary,
    Prophet,

    // Backgrounds for the Lightbearer
    AuspiciousBirth,
    ItinerantMystic,
    SoulOnFire,

    // Backgrounds for the Marshal
    Scion,
    Penitent,
    Luminary,

    // Backgrounds for the Ranger
    MightyHunter,
    WideWanderer,
    BeastBonded,

    // Backgrounds for the Seeker
    Patriot,
    Antiquarian,
    WitchHunter,

    // Backgrounds for the Would-be Hero
    ImpetuousYouth,
    Driven,
    Destined,

    // Special Possessions for the Blessed
    SacredPouchEmMagicalEm,
    Apiary,
    CollectedOfferings,
    GoatHerd,
    HerbGarden,
    Mastiffs,

    // Special Possessions for the Fox
    BurglarsKit,
    CarpentersTools,
    Distillery,
    HiddenStash,
    MummersKit,
    ScribesTools,
    Tannery,
    TradeContacts,

    // Special Possessions for the Heavy
    // Distillery
    ChirurgeonsTools,
    HusbandryTools,
    Smithy,
    StoneworkersTools,
    PhWeaponsOfWar,

    // Special Possessions for the Judge
    YourSymbolOfAuthority,
    // ScribesTools
    Aviary,
    // CarpentersTools
    EngineersTools,
    // Smithy

    // Special Possessions for the Lightbearer
    // Apiary
    BooksScrolls,
    Chandlery,
    // Distillery
    Glassworks,
    HolyRelics,
    LuthiersTools,

    // Special Possessions for the Marshal
    // ChirurgeonsTools
    // Distillery
    // EngineersTools
    PersonalSymbol,
    // ScribesTools
    PmWeaponsOfWar,

    // Special Possessions for the Ranger
    CompositeBow,
    // Distillery
    Hideouts,
    // HusbandryTools
    Hounds,
    LayOfTheLand,
    TrappingGear,

    // Special Possessions for the Seeker
    // ScribesTools
    // BooksScrolls
    // Distillery
    // EngineersTools
    Laboratory,
    Paraphernalia,
    // TradeContacts

    // Special Possessions for the Would-be Hero
    AHeapOfExpectations,
    AGoodDog,
    // HusbandryTools
    // Smithy
    // StoneworkersTools
    PersonalTokenFraughtWithMeaning,
    // Tannery

    // Moves for the Blessed
    FromRaisedByWolves,
    FromVessel,
    AmuletsTalismans,
    Barkskin,
    BigMagic,
    DanusGrasp,
    HealersArts,
    HeedMyWords,
    ImprovedStat,
    IntoTheLionsDen,
    LightningRod,
    RitesOfTheLand,
    SpiritTongue,
    BorrowPower,
    CallTheSpirits,
    TracklessStep,
    Veil,
    WardsBindings,
    WildSoul,
    NaturesWrath,
    PotentWorkings,
    SharedSouls,
    SuckThePoisonOut,
    SuperiorStat,
    VoiceOfTheEarthMother,

    // Moves for the Fox
    FromTheNatural,
    FromTheProdigalReturned,
    AllInTheWrist,
    Ambush,
    Burgle,
    Catlike,
    Dabbler,
    DangerSense,
    FreeRunning,
    // ImprovedStat
    Irresistible,
    LaughAtDanger,
    LightFingers,
    Perceptive,
    RapierWit,
    SkillAtArms,
    ParryRiposte,
    SilverTongued,
    UnderYourSkin,
    BattleDancer,
    CheapShot,
    EyeOnTheDoor,
    PantsOnFire,
    SecondIntent,
    Slippery,
    // SuperiorStat

    // Moves for the Heavy
    FromSheriff,
    FromBloodSoakedPast,
    Armored,
    BattleJoy,
    Berserker,
    CarvedOutOfWood,
    Dangerous,
    Formidable,
    Frosty,
    Guardian,
    // ImprovedStat
    Intimidating,
    HardToKill,
    Unstoppable,
    Musclebound,
    Payback,
    Relentless,
    SeasonedWarrior,
    SituationalAwareness,
    UncannyReflexes,
    Unfettered,
    TerrorOnTheField,
    BringerOfRuin,
    CutFromGranite,
    MightyThews,
    Nemesis,
    SteadfastGuardian,
    StoneCold,
    // SuperiorStat

    // Moves for the Judge
    FromLegacy,
    FromMissionary,
    FromProphet,
    AegisOfFaith,
    // Armored
    BearWitness,
    BreakBread,
    Bulwark,
    Censure,
    Castigate,
    ChroniclerOfStonetop,
    ForTheGreaterGood,
    HoundOfAratis,
    LikeADogWithABone,
    // ImprovedStat
    KnowledgeIsPower,
    ManyHandsMakeLightWork,
    ABundleOfSticksUnbroken,
    TheHammerAndTheBook,
    TruthOrConsequences,
    BindingArbitration,
    VisionUnclouded,
    WellRead,
    AMightyRampart,
    Armistice,
    Condemn,
    Proclamation,
    Mirrorshield,
    // SuperiorStat
    TheTowerEternal,

    // Moves for the Lightbearer
    FromAuspiciousBirth,
    FromItinerantMystic,
    FromSoulOnFire,
    ACandleAgainstTheDark,
    LuminousShield,
    AllIsIlluminated,
    AndBeholdAPaleHorse,
    ConsecratedFlame,
    FireWithin,
    GuidingLight,
    HeliorsUnblinkingEye,
    // ImprovedStat
    InvokeTheSunGod,
    KeepTheHomeFiresBurning,
    Lamplighter,
    Piety,
    PurifyingFlames,
    RadiantCountenance,
    RiseLikeTheSun,
    SpringsFirstThaw,
    BurnTwiceAsBright,
    EmpoweredInvocations,
    GloriousServant,
    HungryFlames,
    LightMoreLight,
    // SuperiorStat
    WielderOfTheWhiteFlame,

    // Moves for the Marshal
    FromPenitent,
    // Armored
    ArtsOfWar,
    Crew,
    VeteranCrew,
    FrontLineLeader,
    // ImprovedStat
    Logistics,
    ReadTheLand,
    PrepareAWelcome,
    SetUpStrike,
    ShakeItOff,
    ShieldWall,
    SirPermissionToDieSir,
    SpeakSoftly,
    Stentorian,
    TakeTheMeasure,
    WeHappyFew,
    BattlefieldGrace,
    HeroesToTheLast,
    FocusFire,
    LikeAnOpenBook,
    NobleMien,
    PeaceThroughStrength,
    // SuperiorStat

    // Moves for the Ranger
    FromWideWanderer,
    FromBeastBonded,
    ASafePlace,
    AnimalCompanion,
    MagnificentSpecimen,
    BigGameHunter,
    BlotOutTheSun,
    CallTheShot,
    ExpertTracker,
    HomeOnTheRange,
    // ImprovedStat
    MentalMap,
    Naturalist,
    OnTheHoof,
    PackHorse,
    Pathfinder,
    Predator,
    SniffOutCorruption,
    Stalker,
    Survivalist,
    WardenOfTheWild,
    WildSpeech,
    Worldly,
    Alpha,
    BeastOfLegend,
    ConstantVigilance,
    GiantSlayer,
    // SuperiorStat
    Trailblazer,
    WalkItOff,

    // Moves for the Seeker
    Attuned,
    ConduitOfPower,
    Countermeasures,
    EverythingBleeds,
    EverythingBurns,
    // ImprovedStat
    InitiateOfTheSecretArts,
    LetsMakeADeal,
    Logbook,
    Magpie,
    NeverAtALoss,
    Polyglot,
    Cryptologist,
    QuickStudy,
    SafetyFirst,
    SageAdvice,
    WellVersed,
    WorkWithWhatYouveGot,
    ArcaneAdept,
    DeepInsight,
    Improvise,
    // SuperiorStat
    MindOverMagic,
    Overchannel,
    ProofAgainstDetection,

    // Moves for the Would-be Hero
    FromImpetuousYouth,
    FromDriven,
    FromDestined,
    AngerIsAGift,
    SpeakTruthToPower,
    BetterPartOfValor,
    IGetKnockedDown,
    ButIGetUpAgain,
    // ImprovedStat
    InOverYourHead,
    IronWill,
    InquiringMinds,
    NeverGonnaKeepMeDown,
    PotentialForGreatness,
    Resourceful,
    SomethingToRememberMeBy,
    ToughLove,
    Underestimated,
    UpWithPeople,
    Versatile,
    AForceToBeReckonedWith,
    BigDamnHero,
    PwSuperiorStat,
    Undaunted,
    VoiceOfExperience,

    // Backstories for the Blessed
    SacredPouch,
    TheEarthMother,

    // Backstories for the Fox
    TallTales,

    // Backstories for the Heavy
    AHistoryOfViolence,

    // Backstories for the Judge
    TheChronicle,
    TheLawkeeper,

    // Backstories for the Lightbearer
    PraiseTheDay,

    // Backstories for the Marshal
    WarStories,

    // Backstories for the Ranger
    SomethingWickedThisWayComes,

    // Backstories for the Seeker
    Collection,
    MajorArcana,
    MinorArcana,

    // Backstories for the Would-be Hero
    FearAnger,
}
pub const THE_BLESSED_MOVES: [ItemKey; 25] = [
    ItemKey::FromRaisedByWolves,
    ItemKey::FromVessel,
    ItemKey::AmuletsTalismans,
    ItemKey::Barkskin,
    ItemKey::BigMagic,
    ItemKey::DanusGrasp,
    ItemKey::HealersArts,
    ItemKey::HeedMyWords,
    ItemKey::ImprovedStat,
    ItemKey::IntoTheLionsDen,
    ItemKey::LightningRod,
    ItemKey::RitesOfTheLand,
    ItemKey::SpiritTongue,
    ItemKey::BorrowPower,
    ItemKey::CallTheSpirits,
    ItemKey::TracklessStep,
    ItemKey::Veil,
    ItemKey::WardsBindings,
    ItemKey::WildSoul,
    ItemKey::NaturesWrath,
    ItemKey::PotentWorkings,
    ItemKey::SharedSouls,
    ItemKey::SuckThePoisonOut,
    ItemKey::SuperiorStat,
    ItemKey::VoiceOfTheEarthMother,
];
pub const THE_FOX_MOVES: [ItemKey; 26] = [
    ItemKey::FromTheNatural,
    ItemKey::FromTheProdigalReturned,
    ItemKey::AllInTheWrist,
    ItemKey::Ambush,
    ItemKey::Burgle,
    ItemKey::Catlike,
    ItemKey::Dabbler,
    ItemKey::DangerSense,
    ItemKey::FreeRunning,
    ItemKey::ImprovedStat,
    ItemKey::Irresistible,
    ItemKey::LaughAtDanger,
    ItemKey::LightFingers,
    ItemKey::Perceptive,
    ItemKey::RapierWit,
    ItemKey::SkillAtArms,
    ItemKey::ParryRiposte,
    ItemKey::SilverTongued,
    ItemKey::UnderYourSkin,
    ItemKey::BattleDancer,
    ItemKey::CheapShot,
    ItemKey::EyeOnTheDoor,
    ItemKey::PantsOnFire,
    ItemKey::SecondIntent,
    ItemKey::Slippery,
    ItemKey::SuperiorStat,
];
pub const THE_HEAVY_MOVES: [ItemKey; 29] = [
    ItemKey::FromSheriff,
    ItemKey::FromBloodSoakedPast,
    ItemKey::Armored,
    ItemKey::BattleJoy,
    ItemKey::Berserker,
    ItemKey::CarvedOutOfWood,
    ItemKey::Dangerous,
    ItemKey::Formidable,
    ItemKey::Frosty,
    ItemKey::Guardian,
    ItemKey::ImprovedStat,
    ItemKey::Intimidating,
    ItemKey::HardToKill,
    ItemKey::Unstoppable,
    ItemKey::Musclebound,
    ItemKey::Payback,
    ItemKey::Relentless,
    ItemKey::SeasonedWarrior,
    ItemKey::SituationalAwareness,
    ItemKey::UncannyReflexes,
    ItemKey::Unfettered,
    ItemKey::TerrorOnTheField,
    ItemKey::BringerOfRuin,
    ItemKey::CutFromGranite,
    ItemKey::MightyThews,
    ItemKey::Nemesis,
    ItemKey::SteadfastGuardian,
    ItemKey::StoneCold,
    ItemKey::SuperiorStat,
];
pub const THE_JUDGE_MOVES: [ItemKey; 30] = [
    ItemKey::FromLegacy,
    ItemKey::FromMissionary,
    ItemKey::FromProphet,
    ItemKey::AegisOfFaith,
    ItemKey::Armored,
    ItemKey::BearWitness,
    ItemKey::BreakBread,
    ItemKey::Bulwark,
    ItemKey::Censure,
    ItemKey::Castigate,
    ItemKey::ChroniclerOfStonetop,
    ItemKey::ForTheGreaterGood,
    ItemKey::HoundOfAratis,
    ItemKey::LikeADogWithABone,
    ItemKey::ImprovedStat,
    ItemKey::KnowledgeIsPower,
    ItemKey::ManyHandsMakeLightWork,
    ItemKey::ABundleOfSticksUnbroken,
    ItemKey::TheHammerAndTheBook,
    ItemKey::TruthOrConsequences,
    ItemKey::BindingArbitration,
    ItemKey::VisionUnclouded,
    ItemKey::WellRead,
    ItemKey::AMightyRampart,
    ItemKey::Armistice,
    ItemKey::Condemn,
    ItemKey::Proclamation,
    ItemKey::Mirrorshield,
    ItemKey::SuperiorStat,
    ItemKey::TheTowerEternal,
];
pub const THE_LIGHTBEARER_MOVES: [ItemKey; 27] = [
    ItemKey::FromAuspiciousBirth,
    ItemKey::FromItinerantMystic,
    ItemKey::FromSoulOnFire,
    ItemKey::ACandleAgainstTheDark,
    ItemKey::LuminousShield,
    ItemKey::AllIsIlluminated,
    ItemKey::AndBeholdAPaleHorse,
    ItemKey::ConsecratedFlame,
    ItemKey::FireWithin,
    ItemKey::GuidingLight,
    ItemKey::HeliorsUnblinkingEye,
    ItemKey::ImprovedStat,
    ItemKey::InvokeTheSunGod,
    ItemKey::KeepTheHomeFiresBurning,
    ItemKey::Lamplighter,
    ItemKey::Piety,
    ItemKey::PurifyingFlames,
    ItemKey::RadiantCountenance,
    ItemKey::RiseLikeTheSun,
    ItemKey::SpringsFirstThaw,
    ItemKey::BurnTwiceAsBright,
    ItemKey::EmpoweredInvocations,
    ItemKey::GloriousServant,
    ItemKey::HungryFlames,
    ItemKey::LightMoreLight,
    ItemKey::SuperiorStat,
    ItemKey::WielderOfTheWhiteFlame,
];
pub const THE_MARSHAL_MOVES: [ItemKey; 25] = [
    ItemKey::FromPenitent,
    ItemKey::Armored,
    ItemKey::ArtsOfWar,
    ItemKey::Crew,
    ItemKey::VeteranCrew,
    ItemKey::FrontLineLeader,
    ItemKey::ImprovedStat,
    ItemKey::Logistics,
    ItemKey::ReadTheLand,
    ItemKey::PrepareAWelcome,
    ItemKey::SetUpStrike,
    ItemKey::ShakeItOff,
    ItemKey::ShieldWall,
    ItemKey::SirPermissionToDieSir,
    ItemKey::SpeakSoftly,
    ItemKey::Stentorian,
    ItemKey::TakeTheMeasure,
    ItemKey::WeHappyFew,
    ItemKey::BattlefieldGrace,
    ItemKey::HeroesToTheLast,
    ItemKey::FocusFire,
    ItemKey::LikeAnOpenBook,
    ItemKey::NobleMien,
    ItemKey::PeaceThroughStrength,
    ItemKey::SuperiorStat,
];
pub const THE_RANGER_MOVES: [ItemKey; 30] = [
    ItemKey::FromWideWanderer,
    ItemKey::FromBeastBonded,
    ItemKey::ASafePlace,
    ItemKey::AnimalCompanion,
    ItemKey::MagnificentSpecimen,
    ItemKey::BigGameHunter,
    ItemKey::BlotOutTheSun,
    ItemKey::CallTheShot,
    ItemKey::ExpertTracker,
    ItemKey::HomeOnTheRange,
    ItemKey::ImprovedStat,
    ItemKey::MentalMap,
    ItemKey::Naturalist,
    ItemKey::OnTheHoof,
    ItemKey::PackHorse,
    ItemKey::Pathfinder,
    ItemKey::Predator,
    ItemKey::SniffOutCorruption,
    ItemKey::Stalker,
    ItemKey::Survivalist,
    ItemKey::WardenOfTheWild,
    ItemKey::WildSpeech,
    ItemKey::Worldly,
    ItemKey::Alpha,
    ItemKey::BeastOfLegend,
    ItemKey::ConstantVigilance,
    ItemKey::GiantSlayer,
    ItemKey::SuperiorStat,
    ItemKey::Trailblazer,
    ItemKey::WalkItOff,
];
pub const THE_SEEKER_MOVES: [ItemKey; 25] = [
    ItemKey::Attuned,
    ItemKey::ConduitOfPower,
    ItemKey::Countermeasures,
    ItemKey::EverythingBleeds,
    ItemKey::EverythingBurns,
    ItemKey::ImprovedStat,
    ItemKey::InitiateOfTheSecretArts,
    ItemKey::LetsMakeADeal,
    ItemKey::Logbook,
    ItemKey::Magpie,
    ItemKey::NeverAtALoss,
    ItemKey::Polyglot,
    ItemKey::Cryptologist,
    ItemKey::QuickStudy,
    ItemKey::SafetyFirst,
    ItemKey::SageAdvice,
    ItemKey::WellVersed,
    ItemKey::WorkWithWhatYouveGot,
    ItemKey::ArcaneAdept,
    ItemKey::DeepInsight,
    ItemKey::Improvise,
    ItemKey::SuperiorStat,
    ItemKey::MindOverMagic,
    ItemKey::Overchannel,
    ItemKey::ProofAgainstDetection,
];
pub const THE_WOULD_BE_HERO_MOVES: [ItemKey; 25] = [
    ItemKey::FromImpetuousYouth,
    ItemKey::FromDriven,
    ItemKey::FromDestined,
    ItemKey::AngerIsAGift,
    ItemKey::SpeakTruthToPower,
    ItemKey::BetterPartOfValor,
    ItemKey::IGetKnockedDown,
    ItemKey::ButIGetUpAgain,
    ItemKey::ImprovedStat,
    ItemKey::InOverYourHead,
    ItemKey::IronWill,
    ItemKey::InquiringMinds,
    ItemKey::NeverGonnaKeepMeDown,
    ItemKey::PotentialForGreatness,
    ItemKey::Resourceful,
    ItemKey::SomethingToRememberMeBy,
    ItemKey::ToughLove,
    ItemKey::Underestimated,
    ItemKey::UpWithPeople,
    ItemKey::Versatile,
    ItemKey::AForceToBeReckonedWith,
    ItemKey::BigDamnHero,
    ItemKey::PwSuperiorStat,
    ItemKey::Undaunted,
    ItemKey::VoiceOfExperience,
];
